### ISSUE TITLE
(Question) Legacy Support for Fedora 3.x

### ISSUE THREAD

**Issue by jrgriffiniii** [cudevmaxwell/sufia-ready-vagrant#5]
Our institution in currently in a position where it would be desirable to deploy a new Sufia application integrated with an existing deployment of the Islandora ecosystem (consisting of, among other technologies, Fedora Commons 3.8.0, Fedora Generic Search 2.7, and Apache Solr 4.2).

Would it at all be helpful to other institutions to support this case?  I do not believe that Islandora-based solutions can be migrated out of Fedora 3.x immediately, and I'm quite certain that other institutions might wish to develop and deploy Sufia within such a heterogenous environment (while waiting for a solution that migrates Islandora content on to Fedora 4).

Thank you for this contribution!

**Comment by cudevmaxwell** [comment]
I think many people will be working with Fedora 3 for years to come, including the kind of heterogeneous environments you describe (though how easy that will be is another issue all together). 

However, I won't be working on this repository any further ( @fatmilktv might take ownership.)  The main sufia developers at https://github.com/projecthydra/sufia would be better folks to ask, they might already be working on vagrants for development on both F3 and F4.
